### ISSUE TITLE
mvc/ListModel返回数据时未考虑接口返回失败情况，导致table初始化报错

### ISSUE THREAD

**Issue by wanglinfang2014** [ecomfe/bat-ria#56]
mvc/ListModel返回数据时未考虑接口返回失败情况，导致table初始化报错

**Comment by chestnutchen** [comment]
恩，这个我了解了，稍后补上。还想问一下，你们请求列表数据是什么场景会导致失败呢？

**Comment by wanglinfang2014** [comment]
场景一：用户没有权限，点击页面后请求list接口直接返回没有权限的提示；
场景二：服务做了请求次数的限制，连续请求5次以上，第六次请求报错。比如连续删除5条数据后，刷新页面请求list接口，list接口报超过请求超限的错误

**Comment by chestnutchen** [comment]
1. 用户没有权限的话，其实应该在更上层做权限控制，`Bat-ria`有权限控制和权限控件的，可以了解一下。
2. 访问次数限制这个场景比较符合这个需求。
3. 这两个场景我感觉其实都可以返回一个重定向的结构体，跳到首页或者一个独立的页面做些提示，类似`NotFoundAction`、`ForbiddenAction`，毕竟已经是不希望用户浏览到数据的场景了。

**Comment by Justineo** [comment]
`bat-ria` 的权限控制那块和锦囊绑定得太紧密了，如果别人要用的话我其实不是很推荐。
场景一的话，权限前端其实可以做验证的，可以设置 `actionConfig` 的 `authority` 属性，然后通过 `er/permission` 模块去做控制的。
场景二的话，后端直接返回 global error 吧？

**Comment by chestnutchen** [comment]
他的意思就是，返回global error之后，他们的页面还是需要给操作。在我们这边其实挂了就挂了，数据都拿不到了。。。

**Comment by leeight** [comment]
+1

**Comment by Justineo** [comment]
老板 +1 的是啥啊……失败以后还要继续操作列表页？

**Comment by leeight** [comment]
+1 的时候没看具体的issue是啥，就是表示关注一下而已~~~

看起来应该是要失败之后有fallback的机制

**Comment by chestnutchen** [comment]
讨论到最后觉得还是属于`访问受限`的场景，返回一个`redirect to 403 page`的消息更严谨点。

**Comment by wanglinfang2014** [comment]
不同场景，需要给用户提示不同的错误信息，如果是redirect其他页面的话，是不是要增加多个的静态提示页面？

**Comment by chestnutchen** [comment]
这一块我再看看`ForbiddenAction`能不能做成可复用的，可以传入不同的提示信息，就比较好了。如果不是`Forbidden`类型的跳转，建议自己再做一个类似`ForbiddenAction`的独立`Action`页来显示吧。

**Comment by wanglinfang2014** [comment]
好的，多谢各位的指导~

**Comment by Justineo** [comment]
@chestnutchen 这个后面可以搞一下，etpl 3.0 开始好像有符合要求的功能。
