### ISSUE TITLE
tpl中提取依赖控件的并自动require的问题

### ISSUE THREAD

**Issue by acelan86** [ecomfe/bat-ria#70]
为啥支持`data-ui-type="Xxx"` 不支持 `data-ui＝"type:Xxx"`？
今天刚被坑，然后没有文档，跟了代码才发现。。

**Comment by chestnutchen** [comment]
具体是哪一个控件呢？之前我也遇到过，记得是特定控件不行，但是后来忘记跟这个问题了。提供一下我去看看

**Comment by Justineo** [comment]
因为正则规则只抓取了 `/data-ui-type="(\w+)"/g`。

可以扩充一下正则为 `/data-ui-type="(\w+)"|data-ui="(?:[^"]*;)?(type:(\w+)\b)/g`，不过后面得改成：

```js
var type = match[1] || match[3];
```

**Comment by acelan86** [comment]
@chestnutchen Table，如果是bat-ria初始化要用到的控件，比如Tab等就可以，可以断点到刚初始化结束没有进入action的时候从esui里面看到可以用的ui

**Comment by otakustay** [comment]
一个HTML属性对应一个控件属性多好，扩展啥嘛……倒是自定义标签可以给加上

**Comment by acelan86** [comment]
@Justineo 谢谢10，我临时用上面的方法改了，测试中，没提pr

**Comment by acelan86** [comment]
@otakustay 写起来麻烦，还长。。。

**Comment by otakustay** [comment]
@acelan86 说白了就是失去了自动`require`的能力，原来已经加载过的还是能正常用的因为esui是会分析`data-ui="xxx"`的

**Comment by otakustay** [comment]
@acelan86 怕写起来长就应该直接上自定义标签，除了少数几个控件外都OK

**Comment by acelan86** [comment]
@otakustay 多谢灰大，是个解决方案，但是感觉需要统一，既然两种都支持，这里感觉也要两种都支持，不然很容易入坑

**Comment by Justineo** [comment]
主要是 ESUI 两种 `data-ui` 的配置方式都支持所以有人掉坑里了。
不过话说本来 `ub-ria` / `bat-ria` 这种就没想让外面团队的人用的……

**Comment by acelan86** [comment]
@Justineo 不要这么把自己限定死啊。。我是死忠啊。。。

**Comment by otakustay** [comment]
嗯，如果这是esui的话我肯定说两者必须支持，这是功能的缺失

不过像`bat-ria`这种，他的使用原本就是建立在团队的开发规范之上的，所以具体就是 @Justineo 的判断了，`ub-ria`的话我肯定就直接不干，因为我们统一就必须分开写，分开写我还能做tpl block复用呢- -

不过我相信 @Justineo 会比我更开放（这锅你背）

**Comment by acelan86** [comment]
（这锅你背）哈哈哈哈。。。行，看两位大神决策了，因为没有对外释放规范，所以我就认为是个缺失了
