### ISSUE TITLE
Uploader的输出格式为URL时支持仅显示文件名

### ISSUE THREAD

**Issue by Justineo** [ecomfe/bat-ria#71]
@neverlandcx

如题，这是因为有时完整URL过长会影响页面显示。

搬运自：https://github.com/ecomfe/esui/issues/494

**Comment by chestnutchen** [comment]
是上传完的时候么，上传完是一个`fake path`，没办法拿到url呀。现在应该都是以文件名优先了。

**Comment by Justineo** [comment]
是这样的，初次加载的时候，`outputType === 'url'` 的时候，没有文件名。可以在 `getFileName()` 的时候先尝试从 URL 最后找下类似 `*.*` 的串作为文件名吧。

**Comment by chestnutchen** [comment]
哦我好像看错问题了。
应该是在setRawValue的时候，尝试填充一下fileName吧。
