### ISSUE TITLE
为什么子action的模板名要用child结尾这么一个规则，如果一个action我既想能够用在主action又能用在子action访问会有什么问题么？

### ISSUE THREAD

**Issue by acelan86** [ecomfe/bat-ria#72]
RT,  求解

**Comment by chestnutchen** [comment]
一个action有可能两种情况都使用了，作为子action的时候，模板有可能和非子action的模板不一样，是为了支持这个功能。

**Comment by otakustay** [comment]
我们这边通常用作子Action的时候会去掉一些面包屑之类的，所以叫`xxxMain`

**Comment by Justineo** [comment]
@otakustay 好像可以用 etpl.getRenderer('xxxMain') 先判断一下是否定义了内嵌用的模板？

**Comment by acelan86** [comment]
@otakustay mini-events还维护么 https://github.com/ecomfe/mini-event/issues/15
