### ISSUE TITLE
FormModel不支持上传文件嘛，应该如何处理？

### ISSUE THREAD

**Issue by galaa2011** [ecomfe/bat-ria#79]

**Comment by chestnutchen** [comment]
上传文件我们是通过`src/ui/Uploader`这个控件来处理的，具体可以看一下这个控件

**Comment by galaa2011** [comment]
Uploader这个控件我看了，我是想在自己的form中添加文件，并与其他信息一起提交。而Uploader貌似是自己创建了一个新的form，并自己提交。

**Comment by Justineo** [comment]
是的，我们这边的逻辑都是文件异步上传好，拿返回的路径和表单一起提交的。因为接口都是 AJAX 的，所以你如果要用 XHR2 做文件提交，那么我们目前的提交流程是没法用的。
